name: 'Sanity checks'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build_test:
    name: 'Build crate for cms'
    runs-on:
      - ubuntu-24.04
    steps:
      # v6.0.2
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - run: |
          set -euxo pipefail
          cargo --version
          cargo build --release --all-features