name: 'Sanity checks'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build_test:
    name: 'Build crate for cms'
    runs-on:
      - ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.1
      - run: |
          set -euxo pipefail
          cargo --version
          cargo build --release --all-features